name: 'Setup Rhino3d'
description: 'Install Rhino3d on the runner'
author: 'McNeel'

inputs:
  email-address: # id of input
    description: 'Email address associated with the user'
    required: true
  release-version: # version to install
    description: 'Release version of Rhino3d to install'
    required: false

#todo: do we need any outputs?

runs:
  using: 'node20'
  main: 'dist/index.js'
